#!/bin/sh
set -e

#DEBHELPER#

case $1 in
    remove)
        conflicts="
        cypress/cyfmac43455-sdio.bin
        cypress/cyfmac43455-sdio.clm_blob
        rtw89/rtw8852b_fw.bin
        r8a779x_usb3_v1.dlmem
        r8a779x_usb3_v2.dlmem
        r8a779x_usb3_v3.dlmem
        "
        for i in $conflicts
        do
            dpkg-divert --package radxa-firmware --rename --remove "/lib/firmware/$i"
        done
        ;;
esac

exit 0